CC=g++
FLAGS=-g
# The -g flag is for debugging info so that the executable can be debugged with GDB.

all: example

example:
	$(CC) -o exampleExecutable main.cpp $(FLAGS)

clean:
	rm -f *.o exampleExecutable *~ core
